version: "3.8"
services:
  nginx:
    depends_on:
      - ws
      - react-app
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "3050:80"
  ws:
    container_name: ws_server
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8181:8181"
  react-app:
    container_name: react_app
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    depends_on:
      - ws
