version: "3.8"
services:
  ws:
    container_name: ws_server
    restart: on-failure
    build:
      context: ./server
      dockerfile: Dockerfile
    volumes:
      - ./server:/app/server
    ports:
      - "8080:8080"
  react-app:
    container_name: react_app
    restart: on-failure
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - ./src:/app/src
    ports:
      - "5173:5173"
    depends_on:
      - ws
