CREATE TABLE IF NOT EXISTS GameData (
    player TEXT NOT NULL,
    week INTEGER NOT NULL,
    wn1 INTEGER NOT NULL,
    wn2 INTEGER NOT NULL,
    wn3 INTEGER NOT NULL,
    wn4 INTEGER NOT NULL,
    wn5 INTEGER NOT NULL,
    pn1 INTEGER NOT NULL,
    pn2 INTEGER NOT NULL,
    pn3 INTEGER NOT NULL,
    pn4 INTEGER NOT NULL,
    pn5 INTEGER NOT NULL
);
